/**
 * ServiceDesk Pro — file attachments.
 *
 * The row records *validated* metadata only. Validation happens in the upload
 * middleware and is deliberately three-layered, because a filename is attacker
 * input:
 *
 *   - **size** — enforced by multer before the bytes are buffered, so an
 *     oversized upload cannot exhaust memory on its way to being refused;
 *   - **MIME type** — checked against an allow-list, never a deny-list;
 *   - **extension** — checked separately *and* cross-checked against the MIME
 *     type, because `report.pdf.exe` and a `.png` claiming to be
 *     `application/x-msdownload` are both cases where trusting one field alone
 *     fails.
 *
 * `storedName` is generated by the server. `originalName` is kept for display
 * only and is never used to build a path — the file on disk never bears a
 * client-supplied name, which closes path traversal at the source rather than
 * trying to sanitise it.
 *
 * `visibility` is copied from the parent comment at upload time. An attachment on
 * an internal note must not appear in the requester's view of their own ticket,
 * and the download route re-checks this field rather than trusting that whatever
 * listed the attachment had filtered correctly.
 */
import { Schema } from 'mongoose';
import { COMMENT_VISIBILITIES, CommentVisibility } from '@shared/enums';
import { BASE_SCHEMA_OPTIONS, defineModel, enumField, ref } from '@/models/helpers';
const attachmentSchema = new Schema({
    storedName: { type: String, required: true, index: false },
    originalName: { type: String, required: true, maxlength: 255 },
    mimeType: { type: String, required: true, maxlength: 160 },
    extension: { type: String, required: true, lowercase: true, maxlength: 16 },
    sizeBytes: { type: Number, required: true, min: 0 },
    ticketId: ref('Ticket', { index: false }),
    commentId: ref('TicketComment', { index: false }),
    uploadedById: ref('User'),
    visibility: enumField(COMMENT_VISIBILITIES, {
        required: true,
        default: CommentVisibility.PUBLIC,
    }),
}, BASE_SCHEMA_OPTIONS);
attachmentSchema.index({ storedName: 1 }, { unique: true });
/** "All attachments on this ticket" — the only listing that exists. */
attachmentSchema.index({ ticketId: 1, createdAt: -1 });
export const Attachment = defineModel('Attachment', attachmentSchema);
