/**
 * ServiceDesk Pro — attachment service.
 *
 * Two responsibilities, and the second is the important one.
 *
 * **Recording an upload.** The bytes are already on disk by the time this runs
 * (multer wrote them), so `record()` only persists the metadata and links it to a
 * ticket or comment. If persisting fails the caller must delete the file — see
 * `discardFiles` in the upload middleware.
 *
 * **Serving a download.** `openForDownload()` re-derives the caller's access from
 * the parent ticket every time rather than trusting the id in the URL. An
 * attachment id is a bearer token otherwise: whoever has the link has the file,
 * including the internal note somebody attached a payslip to. The check mirrors the
 * ticket service exactly — a caller who cannot see the ticket gets the same 404 as
 * for a ticket that does not exist, and an internal attachment is invisible to the
 * requester even on their own ticket.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { AttachmentDto } from '@shared/types';
import { CommentVisibility, Permission } from '@shared/enums';
import { can, isStaff, type ActorContext } from '@/core/actor';
import { env } from '@/config/env';
import { Attachment, Ticket } from '@/models';
import { toObjectId } from '@/models/helpers';
import { NotFoundError, assertFound } from '@/utils/errors';
import { toAttachmentDto } from '@/modules/tickets/ticket.mapper';
import type { AttachmentDoc } from '@/models/attachment.model';
import type { Types } from 'mongoose';

export interface RecordUploadInput {
  file: Express.Multer.File;
  ticketId: Types.ObjectId | string | null;
  commentId?: Types.ObjectId | string | null;
  visibility?: CommentVisibility;
}

/**
 * Persists the metadata for a file multer has already written. `visibility` is
 * copied from the parent comment so the download check has a local field to read
 * instead of joining back to the comment on every request.
 */
export async function record(
  input: RecordUploadInput,
  actor: ActorContext
): Promise<AttachmentDto> {
  const created = await Attachment.create({
    storedName: path.basename(input.file.filename),
    originalName: input.file.originalname.slice(0, 255),
    mimeType: input.file.mimetype,
    extension: path.extname(input.file.originalname).toLowerCase(),
    sizeBytes: input.file.size,
    ticketId: input.ticketId ?? null,
    commentId: input.commentId ?? null,
    uploadedById: toObjectId(actor.user.id),
    visibility: input.visibility ?? CommentVisibility.PUBLIC,
  });

  return toAttachmentDto({
    ...created.toObject(),
    uploadedById: {
      _id: toObjectId(actor.user.id),
      name: actor.user.name,
      email: actor.user.email,
      role: actor.user.role,
    },
  } as never);
}

/** Records several files, keeping their order so the UI lists them as uploaded. */
export async function recordAll(
  files: readonly Express.Multer.File[],
  common: Omit<RecordUploadInput, 'file'>,
  actor: ActorContext
): Promise<AttachmentDto[]> {
  const saved: AttachmentDto[] = [];
  for (const file of files) saved.push(await record({ ...common, file }, actor));
  return saved;
}

/**
 * Resolves an attachment id to a file on disk, or throws the same `NotFoundError`
 * for "no such attachment", "not your ticket" and "internal file, and you are the
 * requester". One error for all three is the point: distinguishing them would
 * confirm the file exists to somebody who may not know that.
 */
export async function openForDownload(
  id: string,
  actor: ActorContext
): Promise<{ absolutePath: string; filename: string; mimeType: string }> {
  const attachment = await Attachment.findById(toObjectId(id));
  const found: AttachmentDoc = assertFound(attachment, 'Attachment');

  await assertVisible(found, actor);

  /* `storedName` was generated by the server, but `basename` is still applied: it
   * costs nothing and means a corrupted row cannot become a path traversal. */
  const absolutePath = path.join(env.uploadDir, path.basename(found.storedName));
  if (!fs.existsSync(absolutePath)) {
    /* The row survived but the file did not. From the caller's side that is the
     * same situation as never having existed. */
    throw new NotFoundError('Attachment');
  }

  return { absolutePath, filename: found.originalName, mimeType: found.mimeType };
}

/** The access rule, shared by download and delete. */
async function assertVisible(attachment: AttachmentDoc, actor: ActorContext): Promise<void> {
  if (attachment.visibility === CommentVisibility.INTERNAL && !isStaff(actor)) {
    throw new NotFoundError('Attachment');
  }

  /* An attachment with no ticket belongs to whoever uploaded it and to staff. */
  if (!attachment.ticketId) {
    const isOwner = String(attachment.uploadedById) === actor.user.id;
    if (!isOwner && !isStaff(actor)) throw new NotFoundError('Attachment');
    return;
  }

  /* Otherwise the ticket decides, using the same scope rule the ticket list uses. */
  const scope = can(actor, Permission.TICKET_READ_ALL)
    ? {}
    : { requesterId: toObjectId(actor.user.id) };
  const ticket = await Ticket.exists({ _id: attachment.ticketId, ...scope });
  if (!ticket) throw new NotFoundError('Attachment');
}
